### PR TITLE
Declare dependencies need to build and install package in setup.py and project.toml

### LINKED ISSUE #127: v8.0.0 requirements
v8.0.0 needs the `distro` and `imaplib2` packages
distro seems to be required by `platform`

#### General informations

- system/distribution (with version): Debian 11
- offlineimap version (`offlineimap -V`): 8.0.0
- Python version: 3.9.2

#### Steps to reproduce the error

- `./env/bin/python -m pip install -v git+https://github.com/offlineIMAP/offlineimap3.git@v8.0.0`

Ref:
https://github.com/OfflineIMAP/offlineimap3/issues/100

### PR DESCRIPTION
**Pull request by alex**
fixes #127

### This PR

> Add character x `[x]`.

- [x] I've read the [DCO](http://www.offlineimap.org/doc/dco.html).
- [x] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html)
- [x] The relevant informations about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [x] Code is tested (provide details).

###

Code was tested with `pip install /tmp/offlineimap3/` until install proceeded successfully.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Oh, you’re quite right. This is good as-is!

**Comment by alex** [comment]
Great, thanks.

**Comment by alex** [comment]
Is there anything I can do to help get this landed?

**Comment by alex** [comment]
Whoops.

**Review by WhyNotHugo — APPROVED** [review]

**Pull request merged**
