### PR TITLE
Fix ConfigParser compatibilty

### PR DESCRIPTION
**Pull request by hugovk**
> This v1.1 template stands in `.github/`.

### This PR

> Add character x `[x]`.

- [ ] I've read the [DCO](http://www.offlineimap.org/doc/dco.html). - no, my browser says the site is not safe
- [ ] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html) - no, as above
- [x] The relevant informations about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [ ] Code is tested (provide details).

### References

https://github.com/python/cpython/pull/92503

### CODE REVIEW

**Comment by hugovk** [comment]
The old `SafeConfigParser` has been removed in Python 3.12, which will be in beta in a week or two, and set for full release in October.

> [configparser](https://docs.python.org/3.12/library/configparser.html#module-configparser) no longer has a SafeConfigParser class. Use the shorter [ConfigParser](https://docs.python.org/3.12/library/configparser.html#configparser.ConfigParser) name instead.

https://docs.python.org/3.12/whatsnew/3.12.html#removed

**Comment by hugovk** [comment]
Closing this year-old PR, but happy to re-open if you'd like OfflineIMAP to work on Python 3.12 (in [beta next week](https://peps.python.org/pep-0693/)).

**Comment by chris001** [comment]
Yes... compatibility with 3.12 would be a very good thing!

**Comment by hugovk** [comment]
Re-opened!

**Comment by serge-sans-paille** [comment]
+1 for merging this in. I've backported the patch to fedora f38

**Comment by thekix** [comment]
Hi,

Sorry about the delay. I think the patches are ok. Should I merge it? 

Best regards,
kix

**Review by thekix — APPROVED** [review]
See #164

**Comment by hugovk** [comment]
Yes, I think this should be merged to support 3.12.

**Pull request merged**
