### PR TITLE
Fix #107 support of UTF-8 inside email

### LINKED ISSUE #107: Invalid encoding causes offlineimap3 to crash
#### General informations

- system/distribution (with version): Debian bookworm/sid
- offlineimap version (`offlineimap -V`):  0.0~git20211018.e64c254+dfsg-1
- Python version: 3.9
-  Debian Bug: https://bugs.debian.org/1004938

#### Logs, error

```
Folder spam [acc: Test]:
 Syncing spam: IMAP -> Maildir
 Copy message UID 1353368115 (1/88) Folk:spam -> Local:spam
 Copy message UID 1353368116 (2/88) Folk:spam -> Local:spam
Copy message from Folk:spam:
 ERROR: Copying message 1353368115 [acc: Test]
  'ascii' codec can't encode characters in position 1541-1579: ordinal not in range(128)
Thread 'Copy message from Folk:spam' terminated with exception:
Traceback (most recent call last):
  File "/usr/share/offlineimap3/offlineimap/threadutil.py", line 146, in run
    Thread.run(self)
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 815, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/share/offlineimap3/offlineimap/folder/Maildir.py", line 409, in savemessage
    tmpname = self.save_to_tmp_file(messagename, msg)
  File "/usr/share/offlineimap3/offlineimap/folder/Maildir.py", line 359, in save_to_tmp_file
    fd.write(msg.as_bytes(policy=output_policy))
  File "/usr/lib/python3.9/email/message.py", line 178, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python3.9/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.9/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.9/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/lib/python3.9/email/generator.py", line 276, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.9/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.9/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.9/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/lib/python3.9/email/generator.py", line 362, in _handle_message
    g.flatten(msg.get_payload(0), unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.9/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.9/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.9/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/lib/python3.9/email/generator.py", line 268, in _handle_multipart
    self.write(subparts)
  File "/usr/lib/python3.9/email/generator.py", line 410, in write
    self._fp.write(s.encode('ascii', 'surrogateescape'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1541-1579: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by catap**
### This PR

- [x] I've read the [DCO](http://www.offlineimap.org/doc/dco.html).
- [x] I've read the [Coding Guidelines](http://www.offlineimap.org/doc/CodingGuidelines.html)
- [x] The relevant informations about the changes stands in the commit message, not here in the message of the pull request.
- [x] Code changes follow the style of the files they change.
- [x] Code is tested (provide details).

### References

- Issue #107 

### Additional information

Introduced by https://github.com/OfflineIMAP/offlineimap3/pull/56

### CODE REVIEW

**Comment by scottkosty** [comment]
Since this is related to #56 would @jishac be well positioned to review it?

**Comment by catap** [comment]
I've encounter such issue on my personal archive of emails, and it allows to download all of them.

Also this patch is a part of distribution for MacPorts which I'm maintainer ;)

**Comment by scottkosty** [comment]
> Also this patch is a part of distribution for MacPorts which I'm maintainer ;)

Ah that is helpful to know. So you mean it has already received a lot of testing?

**Comment by catap** [comment]
@scottkosty or at least some testing :)

**Comment by scottkosty** [comment]
> @scottkosty or at least some testing :)

:) Good to know, thanks!

**Comment by catap** [comment]
@chris001, @nicolas33, @scottkosty  any thoughts?

**Comment by scottkosty** [comment]
> any thoughts?

I'm sorry that I don't know this codebase at all. All I can say is that I've run into this issue a few times and I look forward to it being fixed.

**Comment by chris001** [comment]
> @chris001, @nicolas33, @scottkosty, @jishac any thoughts?

Yes, I'm in favor.  I'm reaching out to @nicolas33 and @thekix for their inputs.  And @jishac , your thoughts?

**Comment by thekix** [comment]
Seems to be fine. I will merge it.

Thanks a lot!
Best regards,
kix

**Comment by catap** [comment]
Thanks!

**Comment by jishac** [comment]
> > @chris001, @nicolas33, @scottkosty, @jishac any thoughts?
> 
> Yes, I'm in favor. I'm reaching out to @nicolas33 and @thekix for their inputs. And @jishac , your thoughts?

Seems fine.

**Pull request merged**
